[package]
name = "tracing-appinsights"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
appinsights = "0.1.5"
thiserror = "1.0.26"
tracing = "0.1.26"
tracing-subscriber = "0.2.20"
